In [0]:
import numpy as np

1.Create a function to check whether numpy array has Zero values or not.

In [0]:
def checkZero(arr):
  if 0 in arr:
      return True
  else:
      return False

arr1 = np.array([[1,2,3],[6,0,7],[11,12,13]])
arr2 = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(checkZero(arr1))
print(checkZero(arr2))



True
False


2.Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [0]:
def meanAndMedian(arr,pass_marks):
    r, = arr.shape
    passed = []
    for i in range(r):
        if arr[i]>=pass_marks:
            passed.append(arr[i])
    passed = np.array(passed)
    passed.sort()
    mean = passed.mean()
    l, = passed.shape
    median = passed[l//2-1] if l%2==0 else passed[l//2]
    return (mean, median)
    
arr = np.array([99,13,32,40,44,90,16,60,70,45]) 
mean, median =  meanAndMedian(arr, 40)
print(f"Mean:{mean}\nMedian:{median}")



Mean:64.0
Median:60


3. Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [0]:
def labelAge(dob):
    labels = {18:'First',19:'Second',20:'Third',21:'Fourth'}
    cur_date = np.datetime64('2019-02-11')
    age = np.array(cur_date-dob)
    age = np.array(age/365,int)
    for a in age:
        if labels.get(a):
          print(f"{a}:{labels[a]}")
    
    

dob = np.array(['2007-07-13', '1999-01-13', '1998-08-13', '1997-03-10', 
                '1999-03-10','1998-04-12','2000-01-01'], dtype='datetime64')
labelAge(dob)



20:Third
20:Third
21:Fourth
19:Second
20:Third
19:Second


4.Create a function to sort 2d Array by a column.

In [0]:
def sortColum(arr, col_ind):
    sort_ind = np.argsort(arr[:,col_ind])
    return arr[sort_ind]
  
arr = np.array([[8,9,1],[7,6,3],[8,8,0],[2,0,1],[3,3,3],[1,7,8]])
sorted_arr = sortColum(arr, 1)
print(sorted_arr)



[[2 0 1]
 [3 3 3]
 [7 6 3]
 [1 7 8]
 [8 8 0]
 [8 9 1]]


5. Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output 

In [0]:
def oneHotEncoding(arr):
    r, = arr.shape
    max_val = arr.max()
    oneHot = np.zeros((r,max_val),int)
    for i in range(r):
        oneHot[i,arr[i]-1] = 1
    return oneHot

oneHot = oneHotEncoding(np.array([2, 3, 2, 2, 2, 1]))
print(oneHot)



[[0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


6.Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [0]:
def dropMissing(arr):
    r, = arr.shape
    new_arr = []
    for i in range(r):
        if not np.isnan(arr[i]):
            new_arr.append(arr[i])
    new_arr = np.array(new_arr)
    return new_arr

arr = np.array([1,2,3,np.nan,5,6,7,np.nan])

print(dropMissing(arr))



[1. 2. 3. 5. 6. 7.]


7.Find Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [0]:
def localMaxima(arr):
    r, = arr.shape
    local_max = []
    for i in range(r-1):
        if(arr[i]>arr[i+1]):
            local_max.append(i)
    local_max = np.array(local_max,)
    return local_max
  
arr = np.array([1,3,7,1,2,6,0,1,2,4,11,0])
print(localMaxima(arr))
        

[ 2  5 10]


8.From the given 1d array arr, generate a 2d matrix using strides,

For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

w and s will be provided by user

In [0]:
def generate2d(arr,w,s):
    r, = arr.shape
    arr2d = []
    for i in range(0,r-w+1,s):
        arr2d.append(arr[i:i+w])
    arr2d = np.array(arr2d)
    return arr2d
  
arr = input("Enter array values:").split()
arr = np.array(arr,int)
w = int(input("Enter window size:"))
s = int(input("Enter strides:"))

arr2d = generate2d(arr,w,s)
print(arr2d)
        

Enter array values:0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
Enter window size:4
Enter strides:2
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14 15]]
